# Generated by Django 4.0.3 on 2023-05-09 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staff',
            options={'ordering': ['-data_angajarii'], 'verbose_name_plural': 'Angajati'},
        ),
        migrations.AlterField(
            model_name='staff',
            name='data_angajarii',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data angajarii'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='functie',
            field=models.CharField(blank=True, choices=[(None, 'Selecteaza functie'), ('paznic', 'paznic'), ('electrician', 'electrician'), ('casier', 'casier'), ('secretara', 'secretara'), ('director', 'director')], max_length=50, null=True, verbose_name='Functie'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='numar',
            field=models.PositiveIntegerField(default=0, verbose_name='Nr Angajat'),
        ),
    ]
