# Generated by Django 4.0.3 on 2023-05-04 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Imagine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=100)),
                ('imagine', models.ImageField(upload_to='galerie/')),
                ('data_creare', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Imagini',
                'ordering': ['-data_creare'],
            },
        ),
    ]
