# Generated by Django 4.0.3 on 2023-05-09 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcare', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagine',
            name='data_creare',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data creare'),
        ),
        migrations.AlterField(
            model_name='imagine',
            name='nume',
            field=models.CharField(max_length=100, verbose_name='Nume Imagine'),
        ),
    ]
