# Generated by Django 4.0.3 on 2023-02-21 15:25

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('useri', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('card_number', models.CharField(max_length=16)),
                ('expiration_month', models.CharField(max_length=2)),
                ('expiration_year', models.CharField(max_length=2)),
                ('cvc', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data_creare', models.DateTimeField(auto_now_add=True)),
                ('numar', models.PositiveIntegerField(default=0)),
                ('pdf', models.FileField(blank=True, null=True, upload_to='facturi/')),
                ('profil', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='useri.profil')),
            ],
            options={
                'verbose_name_plural': 'Facturi',
                'ordering': ['-data_creare'],
            },
        ),
    ]
