# Generated by Django 4.0.3 on 2023-02-21 15:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import useri.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nume', models.CharField(blank=True, max_length=100, null=True)),
                ('prenume', models.CharField(blank=True, max_length=100, null=True)),
                ('cnp', models.CharField(blank=True, max_length=20, null=True)),
                ('judet', models.CharField(blank=True, max_length=20, null=True)),
                ('oras', models.CharField(blank=True, max_length=20, null=True)),
                ('adresa', models.CharField(blank=True, max_length=1000, null=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('telefon', models.CharField(blank=True, max_length=50, null=True)),
                ('imagine', models.ImageField(blank=True, null=True, upload_to=useri.models.user_directory_path)),
                ('data_creare', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Profile',
                'ordering': ['-data_creare'],
            },
        ),
    ]
