# Generated by Django 4.0.3 on 2023-05-09 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useri', '0001_initial'),
        ('clienti', '0002_alter_contract_contract_alter_masina_combustibil_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masina',
            name='combustibil',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Combustibil'),
        ),
        migrations.AlterField(
            model_name='masina',
            name='culoare',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Culoare'),
        ),
        migrations.AlterField(
            model_name='masina',
            name='marca',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Marca'),
        ),
        migrations.AlterField(
            model_name='masina',
            name='model',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Model'),
        ),
        migrations.AlterField(
            model_name='masina',
            name='numar',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Numar'),
        ),
        migrations.AlterField(
            model_name='masina',
            name='profil',
            field=models.ManyToManyField(related_name='Masini', to='useri.profil'),
        ),
    ]
