# Generated by Django 4.0.3 on 2023-05-09 09:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('clienti', '0003_alter_masina_combustibil_alter_masina_culoare_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='categ_permis',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Ctg permis'),
        ),
        migrations.AlterField(
            model_name='client',
            name='data_creare',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data creare'),
        ),
        migrations.AlterField(
            model_name='client',
            name='nr_permis',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Nr permis'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='contract',
            field=models.CharField(blank=True, choices=[(None, 'Selecteaza contract'), ('public', 'Public (500 Lei)'), ('privat', 'Privat (800 Lei)')], max_length=50, verbose_name='Contract'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='data_creare',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data creare'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='data_expirare',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data expirare'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='numar',
            field=models.PositiveIntegerField(default=0, verbose_name='Numar'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='platit',
            field=models.BooleanField(default=False, verbose_name='Platit'),
        ),
        migrations.AlterField(
            model_name='masina',
            name='data_creare',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data creare'),
        ),
    ]
